Implement excel friendly CSV download
elinverd/luminous pull request #11
Opened 2023-07-10 07:10 UTC by Jerryyyz

This pull request aims to fix the problem of not being able to open the CSV without using the `Get Data` button in Excel. The separator would not be recognized and any Greek characters would be in the wrong encoding.

By adding a UTF-8 BOM character and converting the data (with the BOM) to UTF-16, Excel is able to recognize the separator and encoding correctly.

2023-07-17 10:36 UTC, kkentzo commented
The solution should be extended to include the download of CSVs from the Table Hook.

2023-07-17 10:41 UTC, kkentzo requested changes

2023-07-17 10:41 UTC, kkentzo commented on assets/js/components/chartjs_hook.js
> +      csvRows = ['\"time\"\t' + labels.join('\t')]
How is the separator related to the issue at hand (which is encoding-related)? In other words, why are we changing the separator?

2023-07-17 10:41 UTC, kkentzo commented on assets/js/components/chartjs_hook.js
> +      csv = "\ufeff" + csv
I think that a comment regarding what is this character and why we are inserting it here would be useful.

2023-07-17 10:41 UTC, kkentzo commented on assets/js/components/chartjs_hook.js
> +      var byteArray = new Uint8Array(csv.length * 2);
This process of converting the string to UTF-LE16 would perhaps be a good candidate for extracting into a separate function.

2023-07-17 10:41 UTC, kkentzo commented on assets/js/components/chartjs_hook.js
> +        byteArray[i * 2] = csv.charCodeAt(i) // & 0xff;
I guess that the 16-bit UInt returned by `charCodeAt` is truncated here to fit the 8-bit space? It's not obvious to me...

Also, isn't the trailing comment here redundant?

2023-07-17 11:20 UTC, Jewelry-x commented on assets/js/components/chartjs_hook.js
> +      csvRows = ['\"time\"\t' + labels.join('\t')]
> How is the separator related to the issue at hand (which is encoding-related)? In other words, why are we changing the separator?


Excel recognizes tab as a separator rather than comma, so in order for the CSV to be opened easily on Excel the separator used has to be tab. The name of the issue is `Excel friendly CSV download`, which one part of the solution is the tab separator.

2023-08-01 09:38 UTC, tkaretsos commented
We will not proceed with this change, because it adds too much complexity with little value.

2023-08-01 09:38 UTC, closed without merging